networks:
  drivingSchoolNetworks:

services:
  SqlServerDb:
    container_name: SqlServerContainer
    image: mcr.microsoft.com/mssql/server
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password12345

  gvz.laboratory.frontend:
    container_name: GvzLaboratoryFrontend
    image: gvzlaboratoryfrontend
    ports:
      - 3000:3000
    build:
      context: ./Frontend/laboratorygvz.frontend/
      dockerfile: Dockerfile

  gvz.laboratory.userservice:
    container_name: GvzLaboratoryUserService
    image: gvzlaboratoryuserservice
    ports:
      - 5000:8080
    build:
      context: ./Backend/Gvz.Laboratory.UserService
      dockerfile: Dockerfile
    depends_on: 
      - SqlServerDb

  # gvz.laboratory.experimentservice:
  #   container_name: GvzLaboratoryExperimentService
  #   image: gvzlaboratoryexperimentservice
  #   ports:
  #     - 5001:8080
  #   build:
  #     context: ./Backend/Gvz.Laboratory.ExperimentService
  #     dockerfile: Dockerfile
  #   depends_on: 
  #     - SqlServerDb

  gvz.laboratory.manufacturerservice:
    container_name: GvzLaboratoryManufacturerService
    image: gvzlaboratorymanufacturerservice
    ports:
      - 5002:8080
    build:
      context: ./Backend/Gvz.Laboratory.ManufacturerService
      dockerfile: Dockerfile
    depends_on: 
      - SqlServerDb

  gvz.laboratory.supplierservice:
    container_name: GvzLaboratorySupplierService
    image: gvzlaboratorysupplierservice
    ports:
      - 5004:8080
    build:
       context: ./Backend/Gvz.Laboratory.SupplierService
       dockerfile: Dockerfile
    depends_on: 
      - SqlServerDb

  gvz.laboratory.productservice:
    container_name: GvzLaboratoryProductService
    image: gvzlaboratoryproductservice
    ports:
      - 5003:8080
    build:
      context: ./Backend/Gvz.Laboratory.ProductService
      dockerfile: Dockerfile
    depends_on: 
      - SqlServerDb

  gvz.laboratory.researchservice:
        container_name: GvzLaboratoryResearchService
        image: gvzlaboratoryresearchservice
        ports:
          - 5005:8080
        build:
          context: ./Backend/Gvz.Laboratory.ResearchService
          dockerfile: Dockerfile
        depends_on: 
          - SqlServerDb

  zookeeper:
      image: confluentinc/cp-zookeeper:latest
      environment:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://127.0.0.1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MAX_MESSAGE_SIZE: 1048576